### ISSUE TITLE
AJAX - Pb de mise à jour - Paramètre d'une fonction "onclick" non mis à jour

### ISSUE THREAD

**Issue by DiarraDIOP** [DiarraDIOP/Pasteque#6]
J'ai un lien qui, lorsqu'on clique dessus avec la fonction onclick fait appel à une fonction "ShowCategories()". Le but étant d'afficher toutes les catégories à partir q'une requête SQL lorsqu'on clique dessus.
`<a href="#volet" class="ouvrir" onclick="showCategories()" aria-hidden="t`

Voici la fonction showCategories():
![image](https://cloud.githubusercontent.com/assets/14930668/13729011/645a0118-e92a-11e5-8c41-fd7efa907442.png)

qui elle même fait appel à un script PHP qui contient la requête:
Lorsqu'on clique sur une catégorie précise, on veut afficher les produits correspondants avec la fonction showProducts(id) qui prend en param l'id de la catégorie cliquée:

![image](https://cloud.githubusercontent.com/assets/14930668/13729023/a3452ca4-e92a-11e5-9558-3c1c9425836a.png)

Voici la fonction showProducts(id):

![image](https://cloud.githubusercontent.com/assets/14930668/13729025/b816b6de-e92a-11e5-9343-0610ef3f2705.png)

et son script php correspondant:
![image](https://cloud.githubusercontent.com/assets/14930668/13729030/dfaec5d8-e92a-11e5-8779-7a131b01d7f3.png)
![image](https://cloud.githubusercontent.com/assets/14930668/13729033/f1bc8580-e92a-11e5-8cce-6368acc39886.png)

Je regarde mon code source html, tout correspond, les req SQL sont bien et affichent bien les bonnes valeurs de la base (c'est à dire pour chaque catégorie j'ai le bon nom et le bon id rattaché).

Le pb que j'ai est que au clic d'une catégorie au hasard sur mon navigateur, j'obtiens toujours les produits de la catégorie avec l'id 0.

J'ai l'impression que "catégories.php" envoie le bon id en paramètre mais l'id ne se met pas à jour lors de l'appel de la fonction "showProducts"
ps: aucune erreur retournée - Partie bloquante car la gestion de la caisse en dépend

**Comment by AmalBACHARA** [comment]
Problème résolu avec l'ajout de guillemets autour de l'id et ainsi qu'a l'ajout de htmlspecialchars pour les charactere speciaux de l'id
